example1:
	g++ -std=c++14 -c gl.cpp -o gl.o
	g++ -std=c++14 -c example1.cpp -o example1.o
	g++ -std=c++14 -o example1 gl.o example1.o
	rm gl.o example1.o

example2:
	g++ -std=c++14 -c gl.cpp -o gl.o
	g++ -std=c++14 -c example2.cpp -o example2.o
	g++ -std=c++14 -o example2 gl.o example2.o
	rm gl.o example2.o
	